---
driver:
  name: vagrant
  synced_folders:
      - [ './test/integration/default/sample_certs/', '/var/tmp/sample_certs' ]

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[remote-certs::default]
    attributes:
      remote-certs:
        source: 'file:///var/tmp/sample_certs/sample.crt'
        name: 'certificate.crt'
        organization: 'org'
