---
driver:
  name: vagrant
  synced_folders:
      - [ './test/integration/default/sample_certs/', '/var/tmp/sample_certs' ]

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.16.42

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[remote-certs::default]
    attributes:
      remote-certs:
        source: 'file:///var/tmp/sample_certs/cert.pem'
        name: 'certificate.pem'
        organization: 'org'
