---
driver:
  name: vagrant
  synced_folders:
      - [ './sample_certs', '/var/tmp/sample_certs' ]

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[remote-certs::default]
    attributes:
      remote-certs:
        source: 'file:///var/tmp/sample_certs/sample.crt'
        name: 'certificate.crt'
        organization: 'org'
        update_command: '/usr/sbin/update-ca-certificates -f'
