name 'hutch-certs'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures hutch-certs'
long_description 'Installs/Configures hutch-certs'
version '0.1.0'
